config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  resources :users
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 200 }
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  attachment'.' or &. or :: or '['
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image, destroy: false
  validates :name, length: { minimum: 2, maximum: 20 }
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :introduction, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!,except: [:sign_in]
  before_action :ensure_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book)
      flash[:notice]= "Welcome! You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      redirect_to book_path(@book)
      flash[:notice]= "You have updated book successfully"
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def ensure_user
    @books = current_user.books
    @book = @books.find_by(id: params[:id])
    redirect_to books_path unless @book
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      flash[:notice]= "You have updated user successfully"
      redirect_to user_path(current_user)
    else
      @books = @user.books
      @book = Book.new
      render 'edit'
    end
  end

  def destroy
  end

  private

  def ensure_user
    @user = User.find(params[:id])
    if current_user.id != @user.id
    redirect_to user_path(current_user)
    end
  end


  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
 <% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved::
  <% @book.errors.full_messages.each do |message| %>
   <%= message %>
  <% end %>
 <% end %>

<div class="container">
  <div class="row">
   <div class="col-sm-12 col-md-offset-5 col-md-7 col-lg-5 px-5 px-sm-0 mx-auto">
    <h1>Editing Book</h1>
    <%= form_with model:@book,url:"/books/#{@book.id}", local:true do |f| %>
    <p>Title</p>
    <%= f.text_field :title %>
    <p>Opinion</p>
    <%= f.text_field :body %>

    <p>
    <%= f.submit "Update Book", class: "btn btn-success"  %>
    </p>
    <% end %>

    <%= link_to "Show", book_path(@book.id) %>
    <%= link_to "Back", books_path %>
   </div>
  </div>
 </div>

app/views/books/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list', user: current_user,book: @book %>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
     <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      </div>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td><%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg" %></td>
              <% end %>
          </td>
          <td><%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
          </td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
      </tbody>
     </table>
  </div>
  </div>
  </div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
  <%= render 'users/list', user: @user,book: @new_book %>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <tbody>
          <th></th>
          <td><%= link_to user_path(@user.id) do %>
            <%= image_tag('no_image.jpg') %>
            <p><%= @book.user.name %></p>
            <% end %>
          </td>
          <td><%= link_to book_path(@book.id) do %>
            <%= @book.title %>
            <% end %>
          </td>
          <td><%= @book.body %></td>
          <td><% if @user.id == current_user.id %>
            <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-success" %>
            <% end %>
          </td>
          <td><% if @user.id == current_user.id %>
            <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？",class:"btn btn-success destroy(@book.id)" %>
              <% end %>
            </td>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>Bookers2Ver2</title>
    </head>
  <body>
  　<div class="container">
  　<div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
    <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
    </div>
    </div>
    </div>
  </body>
</html>

app/views/homes/top.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>Bookers2Ver2</title>
  </head>
  <body class="vsc-initialized">
<main>
  <p id="notice">Signed out successfully.</p>
    <div class="container">
    <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>
</main>
</body></html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="https://kit.fontawesome.com/1499d187c8.js" crossorigin="anonymous"></script>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body>
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-header w-100">
    <div class="container">
    <ul class="navbar-nav">
      <%= link_to "Bookers", class:'navbarNavDropdown' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </ul>
       <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <div class="social">
          <li class="nav-item">
              <%= link_to "Home", user_path(current_user), class: 'fas fa-home nav-link text-light' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Users', users_path, class: 'fas fa-users nav-link text-light' %>
          </li>
            <li class="nav-item">
              <%= link_to 'Books', books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to 'logout',  destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Home",root_path, class: 'fas fa-home nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "About", home_about_path, class: 'fas fa-link nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "sign up", new_user_registration_path,  class: 'fas fa-user-plus nav-link text-light' %>
            </li>
            <li class="nav-item">
              <%= link_to "login", new_user_session_path,  class: 'fas fa-sign-in-alt nav-link text-light' %>
            </li>
          <% end %>
          </div>
        </ul>
        </div>
      </div>
    </div>
  </nav>
</header>
<%= yield %>

<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
  </body>
</html>

app/views/users/_list.html.erb
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg" %>

        <script src="https://kit.fontawesome.com/1499d187c8.js" crossorigin="anonymous"></script>
        <table class="table">
          <tbody><tr></tr>
            <tr>
              <td>name</td>
              <td><%= user.name %></td>
            </tr>
            <tr>
              <td>introduction</td>
              <td><%= user.introduction %></td>
              </tr>
          </tbody></table>
            <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do %>
            <i class="fas fa-user-cog"></i>
            <% end %>
            <h2 class="mt-3">New book</h2>
            <%= form_with model: book, local:true do |f| %>
              <div class="form-group">
                <p>Title</p>
                <%= f.text_field :title %>
              </div>
              <div class="form-group">
                <p>Opinion</p>
                <%= f.text_area :body %>
              </div>
              <div class="form-group">
                <%= f.submit 'Create Book', class:"btn btn-success" %>
              </div>
            <% end %>
      </div>

app/views/users/edit.html.erb
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %>errors prohibited this obj from being saved:<br></h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<div class="container">
  <div class="row">
   <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto>">
    <h2>User Info</h2>
    <%= form_with model:@user,url:"/users/#{@user.id}", local:true do |f| %>
    <h4>Name</h4>
    <%= f.text_field :name %>
    <h4>Image</h4>
    <%= f.attachment_field :profile_image %>
    <h4>Introduction</h4>
    <%= f.text_field :introduction %>
    <%= f.submit "Update User" %>
    <% end %>
   </div>
  </div>
 </div>

app/views/users/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list', user: @user,book: @book %>
  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
     <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      </div>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show",user_path(user.id) %></td>
        </tr>
        <% end %>
      </tbody>
     </table>
  </div>
</div>

app/views/users/new.html.erb
<h2>Sign up</h2>
<%= form_with model: @user, url: user_registration_path, id: 'new_user', class: 'new_user', local: true do |f| %>

  <%= render "devise/shared/error_messages", resource: resource %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up", class: "btn btn-success" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>
<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>



<div class="container px-5 px-sm-0">
  <div class="row">
    <%= render 'users/list', user: @user,book: @book %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="2"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th></th>
            <% @books.each do |books| %>
            <tr>
              <td><%= link_to user_path(@user.id) do %>
                <%= image_tag('no_image.jpg') %>
                <p><%= books.user.name %></p>
                  <% end %>
              </td>
              <td><%= link_to book_path(books.id) do %>
              <%= books.title %>
              <% end %></td>
              <td><%= books.body %></td>
              <% end %>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>